INSERT INTO ingredients (name) VALUES
    ('all-purpose flour'),
    ('bread flour'),
    ('whole wheat flour'),
    ('sugar'),
    ('brown sugar'),
    ('powdered sugar'),
    ('salt'),
    ('kosher salt'),
    ('sea salt'),
    ('black pepper'),
    ('white pepper'),
    ('olive oil'),
    ('vegetable oil'),
    ('butter'),
    ('unsalted butter'),
    ('eggs'),
    ('milk'),
    ('whole milk'),
    ('heavy cream'),
    ('sour cream'),
    ('cream cheese'),
    ('parmesan cheese'),
    ('cheddar cheese'),
    ('mozzarella cheese'),
    ('garlic'),
    ('onion'),
    ('yellow onion'),
    ('red onion'),
    ('shallot'),
    ('celery'),
    ('carrot'),
    ('potato'),
    ('tomato'),
    ('tomato paste'),
    ('crushed tomatoes'),
    ('bell pepper'),
    ('jalapeno'),
    ('chicken breast'),
    ('chicken thighs'),
    ('ground beef'),
    ('ground pork'),
    ('bacon'),
    ('sausage'),
    ('salmon'),
    ('shrimp'),
    ('rice'),
    ('pasta'),
    ('spaghetti'),
    ('penne'),
    ('chicken broth'),
    ('beef broth'),
    ('vegetable broth'),
    ('soy sauce'),
    ('worcestershire sauce'),
    ('hot sauce'),
    ('vanilla extract'),
    ('baking powder'),
    ('baking soda'),
    ('yeast'),
    ('cinnamon'),
    ('nutmeg'),
    ('paprika'),
    ('cumin'),
    ('oregano'),
    ('basil'),
    ('thyme'),
    ('rosemary'),
    ('parsley'),
    ('cilantro'),
    ('bay leaves'),
    ('lemon'),
    ('lime'),
    ('orange'),
    ('apple'),
    ('banana'),
    ('strawberries'),
    ('blueberries'),
    ('honey'),
    ('maple syrup'),
    ('mayonnaise'),
    ('mustard'),
    ('dijon mustard'),
    ('ketchup'),
    ('vinegar'),
    ('red wine vinegar'),
    ('balsamic vinegar'),
    ('apple cider vinegar'),
    ('coconut milk'),
    ('almond milk'),
    ('spinach'),
    ('kale'),
    ('lettuce'),
    ('broccoli'),
    ('cauliflower'),
    ('zucchini'),
    ('mushrooms'),
    ('green beans'),
    ('corn'),
    ('peas'),
    ('avocado'),
    ('cucumber')
ON CONFLICT (name) DO NOTHING;
